import { tileItem } from "../interfaces";
const tileList: tileItem[] = [
    {
        id: -1,
        position: [-100, -100],
        name: "Barrel",
        tags: ["inside", "furniture"],
        snap: "free",
        src: "./images/barrel.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -2,
        position: [0, 0],
        name: "Wood floor",
        tags: ["inside", "furniture"],
        snap: "snap",
        src: "./images/woodFloor.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -3,
        position: [-100, -100],
        name: "Burger",
        tags: ["inside", "outside", "food"],
        snap: "free",
        src: "./images/burger.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -4,
        position: [-100, -100],
        name: "Bushes",
        tags: ["outside", "plants", "road"],
        snap: "free",
        src: "./images/bushes.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -5,
        position: [-100, -100],
        name: "Candle",
        tags: ["inside", "light"],
        snap: "free",
        src: "./images/candle.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -6,
        position: [-100, -100],
        name: "Window",
        tags: ["inside", "furniture"],
        snap: "free",
        src: "./images/window.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -7,
        position: [-100, -100],
        name: "chair",
        tags: ["inside", "furniture"],
        snap: "free",
        src: "./images/chair.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -8,
        position: [-100, -100],
        name: "Chest",
        tags: ["inside", "outside", "storage"],
        snap: "free",
        src: "./images/chest.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -9,
        position: [-100, -100],
        name: "Flower1",
        tags: ["outside", "inside", "plants"],
        snap: "free",
        src: "./images/Chrysanthemum.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -10,
        position: [-100, -100],
        name: "Cracks",
        tags: ["outside", "cracks"],
        snap: "free",
        src: "./images/cracks.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -11,
        position: [-100, -100],
        name: "Crate",
        tags: ["inside", "outside", "furniture"],
        snap: "free",
        src: "./images/crate.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -12,
        position: [-100, -100],
        name: "Tree1",
        tags: ["outside", "plants"],
        snap: "free",
        src: "./images/tree.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -13,
        position: [-100, -100],
        name: "Door",
        tags: ["inside", "outside", "furniture"],
        snap: "free",
        src: "./images/door.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -14,
        position: [-100, -100],
        name: "Flag",
        tags: ["outside", "decoration"],
        snap: "free",
        src: "./images/flag.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -15,
        position: [0, 0],
        name: "Tile Floor",
        tags: ["inside", "furniture"],
        snap: "snap",
        src: "./images/floor.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -16,
        position: [-100, -100],
        name: "Coin",
        tags: ["inside", "outside", "coin"],
        snap: "free",
        src: "./images/goldCoin.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -17,
        position: [-100, -100],
        name: "Grass",
        tags: ["outside", "plants", "road"],
        snap: "free",
        src: "./images/grass.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -18,
        position: [-100, -100],
        name: "Tree2",
        tags: ["outside", "plants"],
        snap: "free",
        src: "./images/greenTree.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -19,
        position: [-100, -100],
        name: "Stone1",
        tags: ["outside", "stone"],
        snap: "free",
        src: "./images/hugeStone.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -20,
        position: [-100, -100],
        name: "Paper",
        tags: ["inside", "item"],
        snap: "free",
        src: "./images/paper.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -21,
        position: [-100, -100],
        name: "Pasta",
        tags: ["inside", "outside", "food"],
        snap: "free",
        src: "./images/pasta.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -22,
        position: [0, 0],
        name: "Path1",
        tags: ["outside", "road"],
        snap: "snap",
        src: "./images/path.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -23,
        position: [-100, -100],
        name: "Pen",
        tags: ["inside", "item"],
        snap: "free",
        src: "./images/pen.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -24,
        position: [0, 0],
        name: "Pillar",
        tags: ["inside", "outside", "furniture"],
        snap: "snap",
        src: "./images/pillar.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -25,
        position: [-100, -100],
        name: "Pizza",
        tags: ["inside", "outside", "food"],
        snap: "free",
        src: "./images/pizza.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -26,
        position: [-100, -100],
        name: "Flower2",
        tags: ["inside", "outside", "plants"],
        snap: "free",
        src: "./images/redFlowers.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -27,
        position: [-100, -100],
        name: "Rocks",
        tags: ["outside", "stone"],
        snap: "free",
        src: "./images/rocks.png",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -28,
        position: [-100, -100],
        name: "Stone2",
        tags: ["outside", "stone"],
        snap: "free",
        src: "./images/stone.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -29,
        position: [-100, -100],
        name: "Table",
        tags: ["inside", "outside", "furniture"],
        snap: "free",
        src: "./images/table.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    },
    {
        id: -30,
        position: [0, 0],
        name: "Path2",
        tags: ["outside", "road"],
        snap: "snap",
        src: "./images/topPath.jpg",
        scale: 1,
        constScale: 1,
        orientation: 0
    }
];
export default tileList;
